package it.unibo.kBluez.pybluez

enum class PyBluezWrapperState {
    NOT_STARTED, IDLE, SCANNING, LOOKING_UP, FINDING_SERVICES,
    CREATING_SOCKET, BINDING_SOCKET, LISTENING_SOCKET, ACCEPTING_SOCKET,
    RECEIVING_SOCKET, CLOSING_SOCKET, CONNECTING_SOCKET, SENDING_SOCKET,
    GETTING_ADDRESS_SOCKET, SHUTTING_DOWN_SOCKET, SETTING_L2CAP_MTU_SOCKET,
    ADVERTISING_SERVICE, STOP_ADVERTISING,
    TERMINATED
}