package it.unibo.kBluez.pybluez

enum class PyBluezWrapperState {
    NOT_STARTED, IDLE, SCANNING, LOOKING_UP, FINDING_SERVICES,
    CREATING_SOCKET, BINDING_SOCKET, LISTENING_SOCKET, ACCEPTING_SOCKET,
    RECEIVING_SOCKET, CLOSING_SOCKET, CONNECTING_SOCKET, SENDING_SOCKET,
    TERMINATED
}